apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontEnd.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.frontEnd.name }}
    helm.sh/chart: {{ include "chedemo.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.frontEnd.service.type }}
  ports:
    - port: {{ .Values.frontEnd.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ .Values.frontEnd.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backEnd.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.backEnd.name }}
    helm.sh/chart: {{ include "chedemo.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.backEnd.service.type }}
  ports:
    - port: {{ .Values.backEnd.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ .Values.backEnd.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.database.name }}
    helm.sh/chart: {{ include "chedemo.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.database.service.type }}
  ports:
    - port: {{ .Values.database.service.port }}
      # targetPort: http
      protocol: TCP
      name: mysql
  selector:
    app.kubernetes.io/name: {{ .Values.database.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
